version: '3'
services:
  pokedex:
    environment:
      - port=3000
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./src:/app/src
      - ./public:/app/public
